title: Yilan Bu's Homepage
page-top-title: Yilan Bu
top-section-bg-text: Spatial Data Science (Data Science)
home-subtitle: Yilan Bu&ensp;|&ensp;卜一兰
copyright-text: '&copy; Yilan Bu 2024-2025. All Rights Reserved.'
